export { fontFamily } from './Others/FontFamily'
export { hp, wp } from './Others/Scalling'
export { GColor } from './Others/Theme'
export { fontSize } from './Others/Typography'
export { GButton } from './Styles/GButton'
export { GTextInput } from './Styles/GTextInput'
export { GStyles } from './Styles/GStyles'
export { GIcons } from './Others/Icons'